### ISSUE TITLE
get_regions() raises an error

### ISSUE THREAD

**Issue by mbjoseph** [TrashBirdEcology/bbsAssistant#51]
Hey @TrashBirdEcology! Awesome package. Maybe this is a bug? :man_shrugging: 

**Describe the bug**

The `get_regions()` function raises an error that seems to be caused by attempting to read a `README.txt` file from the FTP server that no longer exists. 

**To Reproduce**

``` r
library(bbsAssistant)
regions <- get_regions()
#> Parsed with column specification:
#> cols(
#>   X1 = col_character(),
#>   X2 = col_character()
#> )
#> Parsed with column specification:
#> cols(
#>   X1 = col_character(),
#>   X2 = col_character(),
#>   X3 = col_character()
#> )
#> Warning in dir.create(codesDir): '/tmp/RtmpHiEJfU/reprex156458487ca2/
#> bbsData/codes' already exists
#> Warning in download.file(url = File, destfile = paste0(codesDir, "/
#> README.txt")): cannot open URL 'ftp://ftpext.usgs.gov/pub/er/md/laurel/BBS/
#> DataFiles/README.txt': FTP status was '550 Requested action not taken; file
#> unavailable'
#> Error in download.file(url = File, destfile = paste0(codesDir, "/README.txt")): cannot open URL 'ftp://ftpext.usgs.gov/pub/er/md/laurel/BBS/DataFiles/README.txt'
```

<sup>Created on 2019-08-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Expected behavior**

I was expecting to get the region data, like in the README. 

**Session info**

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Pop!_OS 18.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bbsAssistant_1.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2      rstudioapi_0.10 whisker_0.3-2   knitr_1.24      magrittr_1.5    hms_0.5.0       here_0.1        R6_2.4.0        rlang_0.4.0    
[10] tools_3.6.1     packrat_0.5.0   xfun_0.8        withr_2.1.2     clipr_0.7.0     htmltools_0.3.6 rprojroot_1.3-2 digest_0.6.20   tibble_2.1.3   
[19] crayon_1.3.4    processx_3.4.1  callr_3.3.1     readr_1.3.1     ps_1.3.0        vctrs_0.2.0     fs_1.3.1        curl_4.0        zeallot_0.1.0  
[28] evaluate_0.14   rmarkdown_1.14  reprex_0.3.0    compiler_3.6.1  pillar_1.4.2    backports_1.1.4 pkgconfig_2.0.2
```

**Additional context**

The error seems to stem from this file not existing: ftp://ftpext.usgs.gov/pub/er/md/laurel/BBS/DataFiles/README.txt

Maybe it was removed in the most recent BBS data update?

**Comment by trashbirdecology** [comment]
Max, Thanks for reaching out. Unfortunately the BBS recently overhauled
their website, rendering some functions defunct. We are actively working on
the updates now. Feel free to clone the branch `add_data`. Otherwise, we
will release a new update in a few days, hopefully, which should solve all
existing bugs.

Thanks for reaching out!


________________________________________________________________

Jessica L. Burnett
School of Natural Resources
University of Nebraska-Lincoln
+1.352.792.5425

GitHub <http://github.com/trashbirdecology>
CV/Resume
<https://github.com/TrashBirdEcology/cv/blob/master/burnett_extendedCV.pdf>
Nebraska Cooperative Fish & Wildlife Research Unit
<http://snr.unl.edu/necoopunit/>
ORC ID: 0000-0002-0896-5099 <https://orcid.org/0000-0002-0896-5099>
________________________________________________________________



<http://snr.unl.edu/necoopunit/>

**Comment by mbjoseph** [comment]
Awesome! Thanks @TrashBirdEcology :+1:

**Comment by trashbirdecology** [comment]
@mbjoseph , I have updated the vignette and package to reflect these changes. Please let me know if you run into any other issues, or have additional recommendations! Thanks again
